"""Embedding + indexing pipeline: chunk objects -> FAISS vectorstore."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

from src.config import CHUNKS_DIR, EMBEDDING_MODEL, VECTORSTORE_DIR


@dataclass(frozen=True)
class VectorStoreArtifactPaths:
    index_path: Path
    metadata_path: Path
    manifest_path: Path


def load_chunk_records(chunks_file: Path) -> list[dict[str, Any]]:
    """Load chunk JSONL generated by chunk.py."""
    if not chunks_file.exists():
        raise FileNotFoundError(f"Chunks file not found: {chunks_file}")

    records: list[dict[str, Any]] = []
    with chunks_file.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))

    if not records:
        raise ValueError(f"No chunk records found in {chunks_file}")
    return records


def filter_records_by_subject(records: list[dict[str, Any]], subject: str | None = None) -> list[dict[str, Any]]:
    """Optionally filter chunks for one subject."""
    if not subject:
        return records
    subject = subject.lower().strip()
    filtered = [record for record in records if str(record.get("subject", "")).lower() == subject]
    if not filtered:
        raise ValueError(f"No chunks found for subject '{subject}'")
    return filtered


def build_embedding_model(model_name: str = EMBEDDING_MODEL) -> SentenceTransformer:
    """Create SentenceTransformer encoder.

    Design choice:
    - `all-MiniLM-L6-v2` is lightweight and fast on CPU while giving strong
      semantic retrieval quality for study-note style text.
    """
    return SentenceTransformer(model_name)


def embed_texts(
    texts: list[str],
    model: SentenceTransformer,
    batch_size: int = 64,
    normalize: bool = True,
) -> np.ndarray:
    """Convert texts to float32 embedding matrix."""
    embeddings = model.encode(
        texts,
        batch_size=batch_size,
        convert_to_numpy=True,
        normalize_embeddings=normalize,
        show_progress_bar=True,
    )
    return np.asarray(embeddings, dtype=np.float32)


def build_faiss_index(embeddings: np.ndarray, use_cosine: bool = True) -> faiss.Index:
    """Build FAISS index from embeddings.

    Design choice:
    - Use `IndexFlatIP` with normalized vectors to emulate cosine similarity.
      This is simple, exact, and reliable for v1 sized corpora.
    """
    if embeddings.ndim != 2:
        raise ValueError("Embeddings must be a 2D matrix")

    dim = embeddings.shape[1]
    if dim <= 0:
        raise ValueError("Invalid embedding dimension")

    index = faiss.IndexFlatIP(dim) if use_cosine else faiss.IndexFlatL2(dim)
    index.add(embeddings)
    return index


def save_metadata(records: list[dict[str, Any]], metadata_path: Path) -> None:
    """Persist metadata in index-order alignment with vectors."""
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    with metadata_path.open("w", encoding="utf-8") as file:
        for record in records:
            # Keep all chunk metadata, excluding text to reduce disk footprint.
            compact = {k: v for k, v in record.items() if k != "text"}
            file.write(json.dumps(compact, ensure_ascii=False) + "\n")


def save_manifest(
    manifest_path: Path,
    *,
    model_name: str,
    total_vectors: int,
    embedding_dim: int,
    similarity: str,
    source_chunks_file: Path,
) -> None:
    """Persist build metadata for traceability and reproducibility."""
    manifest = {
        "model_name": model_name,
        "total_vectors": total_vectors,
        "embedding_dim": embedding_dim,
        "similarity": similarity,
        "source_chunks_file": str(source_chunks_file),
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def build_vector_index(
    chunks_dir: Path = CHUNKS_DIR,
    vectorstore_dir: Path = VECTORSTORE_DIR,
    model_name: str = EMBEDDING_MODEL,
    subject: str | None = None,
    batch_size: int = 64,
) -> VectorStoreArtifactPaths:
    """Generate embeddings and store FAISS index + aligned metadata."""
    chunks_file = chunks_dir / "chunks.jsonl"
    artifacts = VectorStoreArtifactPaths(
        index_path=vectorstore_dir / "faiss.index",
        metadata_path=vectorstore_dir / "metadata.jsonl",
        manifest_path=vectorstore_dir / "manifest.json",
    )

    all_records = load_chunk_records(chunks_file)
    records = filter_records_by_subject(all_records, subject=subject)
    texts = [str(record.get("text", "")).strip() for record in records]
    if any(not text for text in texts):
        raise ValueError("Found empty chunk text; fix chunk generation before embedding")

    model = build_embedding_model(model_name=model_name)
    embeddings = embed_texts(texts, model=model, batch_size=batch_size, normalize=True)
    index = build_faiss_index(embeddings, use_cosine=True)

    vectorstore_dir.mkdir(parents=True, exist_ok=True)
    faiss.write_index(index, str(artifacts.index_path))
    save_metadata(records, artifacts.metadata_path)
    save_manifest(
        artifacts.manifest_path,
        model_name=model_name,
        total_vectors=len(records),
        embedding_dim=int(embeddings.shape[1]),
        similarity="cosine_via_inner_product_on_normalized_vectors",
        source_chunks_file=chunks_file,
    )
    return artifacts


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate embeddings and FAISS index for chunked notes.")
    parser.add_argument("--chunks-dir", type=Path, default=CHUNKS_DIR)
    parser.add_argument("--vectorstore-dir", type=Path, default=VECTORSTORE_DIR)
    parser.add_argument("--model", default=EMBEDDING_MODEL, help="SentenceTransformer model name.")
    parser.add_argument("--subject", help="Optional subject filter (e.g. os, java).")
    parser.add_argument("--batch-size", type=int, default=64)
    return parser


def main() -> int:
    args = _build_parser().parse_args()
    artifacts = build_vector_index(
        chunks_dir=args.chunks_dir,
        vectorstore_dir=args.vectorstore_dir,
        model_name=args.model,
        subject=args.subject,
        batch_size=args.batch_size,
    )
    print(f"Index saved: {artifacts.index_path}")
    print(f"Metadata saved: {artifacts.metadata_path}")
    print(f"Manifest saved: {artifacts.manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
